### PR TITLE
require Nim 2.0

### PR DESCRIPTION
**Pull request by tersec**

### CODE REVIEW

**Comment by arnetheduck** [comment]
ditto..

**Comment by tersec** [comment]
https://github.com/status-im/status-desktop/tree/master/vendor doesn't use this repo.

**Comment by arnetheduck** [comment]
nevertheless, since there's no concrete reason to drop 1.6 (ie a specific bug or feature), it's better to keep the option open since we're aiming to integrate more of Nimbus into there and elsewhere, also in community projects.

Snappy in particular sees very little maintenance / changes  it's quite stable as-is. 

One of its selling points is the ease of integrating it into projects which would be limited by a narrow nim version support requirement. If we need to make an overhaul, that would be a good time to drop support as well.

**Comment by narimiran** [comment]
Here is a less controversial version of these changes: https://github.com/status-im/nim-snappy/pull/30

**Comment by narimiran** [comment]
With #30 merged, it is ok to close this one.

**Pull request closed without merging**
